apiVersion: v1                 
kind: ConfigMap                
metadata:
  name: app-config
data:
  # База данных
  POSTGRES_HOST: "{{ .Values.config.POSTGRES_HOST }}"
  POSTGRES_PORT: "{{ .Values.config.POSTGRES_PORT }}"
  SESSION_DB: "{{ .Values.config.SESSION_DB }}"
  HOTEL_DB: "{{ .Values.config.HOTEL_DB }}"
  BOOKING_DB: "{{ .Values.config.BOOKING_DB }}"
  PAYMENT_DB: "{{ .Values.config.PAYMENT_DB }}"
  LOYALTY_DB: "{{ .Values.config.LOYALTY_DB }}"
  REPORT_DB: "{{ .Values.config.REPORT_DB }}"
  SESSION_SERVICE_URL: "{{ .Values.config.SESSION_SERVICE_URL }}"
  HOTEL_SERVICE_URL: "{{ .Values.config.HOTEL_SERVICE_URL }}"
  BOOKING_SERVICE_URL: "{{ .Values.config.BOOKING_SERVICE_URL }}"
  LOYALTY_SERVICE_URL: "{{ .Values.config.LOYALTY_SERVICE_URL }}"
  REPORT_SERVICE_URL: "{{ .Values.config.REPORT_SERVICE_URL }}"
  
  # RabbitMQ
  RABBIT_MQ_HOST: "{{ .Values.config.RABBIT_MQ_HOST }}"
  RABBIT_MQ_PORT: "{{ .Values.config.RABBIT_MQ_PORT }}"
  RABBIT_MQ_QUEUE_NAME: "{{ .Values.config.RABBIT_MQ_QUEUE_NAME }}"
  RABBIT_MQ_EXCHANGE: "{{ .Values.config.RABBIT_MQ_EXCHANGE }}"

  # Адреса сервисов
  SESSION_SERVICE_HOST: "{{ .Values.config.SESSION_SERVICE_HOST }}"
  SESSION_SERVICE_PORT: "{{ .Values.config.SESSION_SERVICE_PORT }}"
  HOTEL_SERVICE_HOST: "{{ .Values.config.HOTEL_SERVICE_HOST }}"
  HOTEL_SERVICE_PORT: "{{ .Values.config.HOTEL_SERVICE_PORT }}"
  PAYMENT_SERVICE_HOST: "{{ .Values.config.PAYMENT_SERVICE_HOST }}"
  PAYMENT_SERVICE_PORT: "{{ .Values.config.PAYMENT_SERVICE_PORT }}"
  LOYALTY_SERVICE_HOST: "{{ .Values.config.LOYALTY_SERVICE_HOST }}"
  LOYALTY_SERVICE_PORT: "{{ .Values.config.LOYALTY_SERVICE_PORT }}"
  BOOKING_SERVICE_HOST: "{{ .Values.config.BOOKING_SERVICE_HOST }}"
  BOOKING_SERVICE_PORT: "{{ .Values.config.BOOKING_SERVICE_PORT }}"
  REPORT_SERVICE_HOST: "{{ .Values.config.REPORT_SERVICE_HOST }}"
  REPORT_SERVICE_PORT: "{{ .Values.config.REPORT_SERVICE_PORT }}"

  # UUID (несекретные)
  GATEWAY_SERVICE_UUID: "{{ .Values.config.GATEWAY_SERVICE_UUID }}"
  BOOKING_SERVICE_UUID: "{{ .Values.config.BOOKING_SERVICE_UUID }}"

