apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
  labels:
    app: hotel
spec:
  replicas: {{ .Values.replicaCount.hotel }}
  selector:
    matchLabels:
      app: hotel
  template:
    metadata:
      labels:
        app: hotel
    spec:
      containers:
      - name: hotel
        image: {{ .Values.image.hotel }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.config.POSTGRES_HOST | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.config.POSTGRES_PORT | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.config.HOTEL_DB | quote }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_PASSWORD
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PRIVATE_KEY
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PUBLIC_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP