apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: {{ .Values.replicaCount.payment }}
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: {{ .Values.image.payment }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.config.POSTGRES_HOST | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.config.POSTGRES_PORT | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.config.PAYMENT_DB | quote }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_PASSWORD
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PRIVATE_KEY
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PUBLIC_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP