apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  RABBIT_MQ_USER: {{ .Values.secrets.RABBIT_MQ_USER | b64enc }}
  RABBIT_MQ_PASSWORD: {{ .Values.secrets.RABBIT_MQ_PASSWORD | b64enc }}
  PRIVATE_KEY: {{ .Values.secrets.PRIVATE_KEY | b64enc }}
  PUBLIC_KEY: {{ .Values.secrets.PUBLIC_KEY | b64enc }}