apiVersion: apps/v1
kind: Deployment
metadata:
  name: session
  labels:
    app: session
spec:
  replicas: {{ .Values.replicaCount.session }}
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
    spec:
      containers:
      - name: session
        image: {{ .Values.image.session }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.config.POSTGRES_HOST | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.config.POSTGRES_PORT | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.config.SESSION_DB | quote }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_PASSWORD
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PRIVATE_KEY
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PUBLIC_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  selector:
    app: session
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP