apiVersion: v1                 
kind: ConfigMap                
metadata:
  name: app-config
data:
  # База данных
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  SESSION_DB: "users_db"
  HOTEL_DB: "hotels_db"
  BOOKING_DB: "reservations_db"
  PAYMENT_DB: "payments_db"
  LOYALTY_DB: "balances_db"
  REPORT_DB: "statistics_db"
  SESSION_SERVICE_URL: "http://session-service:8081/api/v1/auth"
  HOTEL_SERVICE_URL: "http://hotel-service:8082/api/v1/hotels"
  BOOKING_SERVICE_URL: "http://booking-service:8083/api/v1/booking"
  LOYALTY_SERVICE_URL: "http://loyalty-service:8085/api/v1/loyalty"
  REPORT_SERVICE_URL: "http://report-service:8086/api/v1/report"
  
  # RabbitMQ
  RABBIT_MQ_HOST: "rabbitmq"
  RABBIT_MQ_PORT: "5672"
  RABBIT_MQ_QUEUE_NAME: "booking.queue"
  RABBIT_MQ_EXCHANGE: "booking.exchange"

  # Адреса сервисов
  SESSION_SERVICE_HOST: "session-service"
  SESSION_SERVICE_PORT: "8081"
  HOTEL_SERVICE_HOST: "hotel-service"
  HOTEL_SERVICE_PORT: "8082"
  PAYMENT_SERVICE_HOST: "payment-service"
  PAYMENT_SERVICE_PORT: "8084"
  LOYALTY_SERVICE_HOST: "loyalty-service"
  LOYALTY_SERVICE_PORT: "8085"
  BOOKING_SERVICE_HOST: "booking-service"
  BOOKING_SERVICE_PORT: "8083"
  REPORT_SERVICE_HOST: "report-service"
  REPORT_SERVICE_PORT: "8086"
  # UUID (несекретные)
  GATEWAY_SERVICE_UUID: "b51ceda2-bfa5-11eb-8529-0242ac130003"
  BOOKING_SERVICE_UUID: "911ccb4c-c055-11eb-8529-0242ac130003"

